data_root: /home/apsk14/data/final_data/Table/Table.train # Path to chairs training dataset.
stat_root: /media/data1/apsk14/srn_seg_data/Table/Table.train #Path to stats for assigning label data
val_root: /home/apsk14/data/final_data/Table/Table.test
#val_stat_root: /media/data1/apsk14/srn_seg_data/Table/Table.test
checkpoint_path: /media/data3/apsk14/srn_new_logging/Table/train_vanilla/checkpoints/epoch_0008_iter_105000.pth
validation_path: /media/data3/apsk14/srn_new_logging/Table/latent_vanilla_single/checkpoints/epoch_1005_iter_080000.pth
img_sidelengths: 128
batch_size_per_img_sidelength: 15 # This is for a GPU with 48 GB of memory. Adapt accordingly for your GPU memory.
max_steps_per_img_sidelength: 170000
obj_name: Table
class_weight: 8
overwrite_embeddings: True

