data_root: /media/data2/apsk14/srn_rendered_data/Lamp/Lamp.train # Path to chairs training dataset.
stat_root: /media/data2/apsk14/srn_model_data/Lamp/Lamp.train #Path to stats for assigning label data
val_root: /media/data2/apsk14/srn_rendered_data/Lamp/Lamp.train_val # Path to chairs validation set
logging_root: /media/data2/apsk14/logging/Lamp
img_sidelengths: 128
batch_size_per_img_sidelength: 32 # This is for a GPU with 48 GB of memory. Adapt accordingly for your GPU memory.
max_steps_per_img_sidelength: 170000
num_classes: 18
obj_name: Lamp
class_weight: 8
