data_root: /home/apsk14/data/final_data/Table/Table.train # Path to chairs training dataset.
#val_root: /home/apsk14/data/final_data/Chair/Chair.val # Path to chairs training dataset.
stat_root: /media/data1/apsk14/srn_seg_data/Table/Table.train #Path to stats for assigning label data
logging_root: /media/data3/apsk14/srn_new_logging/Table/tart_train
img_sidelength: 128
obj_name: Table
batch_size: 128
preload: True
no_validation: True
num_classes: 11
