data_root: /home/apsk14/data/final_data/Chair/Chair.train # Path to chairs training dataset.
#val_root: /home/apsk14/data/final_data/Chair/Chair.val # Path to chairs training dataset.
stat_root: /media/data1/apsk14/srn_seg_data/Chair/Chair.train #Path to stats for assigning label data
logging_root: /media/data3/apsk14/srn_new_logging/Chair/tart_train
img_sidelength: 128
obj_name: Chair
batch_size: 128
preload: True
no_validation: True
num_classes: 6
#checkpoint_path: /media/data2/sitzmann/srn-segmentation/chairs_tatarchenko/checkpoints/epoch_0025_iter_045000.pth
#start_step: 45000
