obj_name: Table
data_root: /media/hugespace/amit/semantic_srn_data/Table/Table.train # Path to chairs training dataset.
logging_root: /media/hugespace/amit/srn_logging/Table # Path to chairs training dataset.


